name: Daily Update Nuclei POCs

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: 1 Clone Repos
      run: python 1-clone_repos.py

    - name: 2 Download Nuclei
      run: |
        pip install requests
        python 2-download_nuclei.py
        unzip nuclei.zip nuclei
        chmod +x nuclei
        rm -rf nuclei.zip

    - name: 3 Check POC
      run: |
        POC_DIR="clone-templates"
        if [ ! -d "$POC_DIR" ]; then
          echo "$POC_DIR 文件夹不存在，跳过检查。"
          exit 0
        fi
        for file in "$POC_DIR"/*.yml "$POC_DIR"/*.yaml; do
          if [ ! -e "$file" ]; then
            echo "未找到 YAML 文件，跳过。"
            break
          fi
          echo "检查 POC $file 中..."
          result=$(./nuclei -t "$file" -silent 2>&1)
          if echo "$result" | grep -q "FTL"; then
            echo "$file 格式无效，已删除。"
            rm -f "$file"
          else
            echo "$file 格式有效。"
          fi
        done

    - name: 4 Move Duplicated
      run: python 4-remove_duplicated.py

    - name: 5 Get POC Name
      run: python 5-get_pocname.py

    - name: 6 Delete Nuclei
      run: rm -rf nuclei
